version: "3.8"

services:
  web:
    build: "./web"
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_HOST=http://localhost:8001/api/
  api:
    build: "./api"
    ports:
      - "8001:8001"
    depends_on:
      - "web"
