version: "3.8"

services:
  web:
    build: "./web"
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_HOST=http://localhost:8001/
    # volumes:
    #   - "./web:/web"
  api:
    build: "./api"
    ports:
      - "8001:8001"
    # volumes:
    #   - "./api:/api"
    depends_on:
      - "web"
